# Module1 - Exercise 1: Creating Different Types of NumPy Arrays

In [2]:
#1D array
import numpy as np

a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


In [3]:
#2D array
import numpy as np

b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [4]:
#3D array
import numpy as np

c = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(c)
print(c[1,0,0])
print(c.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
7
(2, 2, 3)


In [5]:
#5*5 matrix with ones
import numpy as np

d = np.ones((5,5),dtype=int)
print(d)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [6]:
#array with values from 0 to 20 with a step of 2

import numpy as np

e = np.arange(0, 21, 2)
print(e)
#append
f = np.delete(e, [-1,-2])
print(f)
g = f.reshape(3,3)
print(g)
g[1,1] = 99
print(g)

[ 0  2  4  6  8 10 12 14 16 18 20]
[ 0  2  4  6  8 10 12 14 16]
[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]
[[ 0  2  4]
 [ 6 99 10]
 [12 14 16]]


# Module1 - Exercise 2: Understanding Array Properties

In [7]:
#print size
import numpy as np

a = np.array([1, 2, 3, 4, 5])
print(a.size)

5


In [8]:
#print shape
import numpy as np

b = np.array([[1, 2, 3], [4, 5, 6]])
print(b.shape)

(2, 3)


In [9]:
#print dtype
import numpy as np

c = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]],dtype=int)
print(c)
print(c.dtype)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
int64


In [10]:
#Convert data type of an array from int to float
import numpy as np

a = np.array([1, 2, 3, 4, 5])
print(a)
a = a.astype(float)
print(a)


[1 2 3 4 5]
[1. 2. 3. 4. 5.]


# Module 2 - Exercise 1: Create two NumPy arrays of shape (3,3), fill them with random values, and perform element-wise addition, subtraction, multiplication, and division.

In [11]:
a = np.random.randint(1,9,(3,3))
b = np.random.randint(1,9,(3,3))
print(a)
print(b)
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[6 5 3]
 [5 2 6]
 [4 3 8]]
[[5 1 8]
 [5 8 4]
 [5 6 6]]
[[11  6 11]
 [10 10 10]
 [ 9  9 14]]
[[ 1  4 -5]
 [ 0 -6  2]
 [-1 -3  2]]
[[30  5 24]
 [25 16 24]
 [20 18 48]]
[[1.2        5.         0.375     ]
 [1.         0.25       1.5       ]
 [0.8        0.5        1.33333333]]


# Module 2 - Exercise 2: Demonstrate broadcasting by adding a 1D array [1, 2, 3] to a 3x3 matrix.

In [12]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([1, 2, 3])
print(a)
print(b)
print(a+b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


# Module 2 - Exercise 3: Compute the dot product of two vectors and multiply two 2x2 matrices.

In [13]:
import numpy as np

a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
print(a)
print(b)
print(np.dot(a,b))
print(a*b)

[1 2 3 4]
[5 6 7 8]
70
[ 5 12 21 32]


# Module 3 - Exercise 1: Create a 5x5 NumPy array with values ranging from 1 to 25.


In [14]:
import numpy as np

a = np.linspace(1,25,25,dtype=int)
print(a)
a = a.reshape(5,5)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [15]:
import numpy as np

a = np.arange(1,26).reshape(5,5)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


# Module 3 - Exercise 2: Extract the middle row and middle column.

In [16]:
import numpy as np

a = np.arange(1,26).reshape(5,5)
print(a)
print(a[2,2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
13


# Module3 - Exercise 3: Select all even numbers from the array using masking

In [17]:
import numpy as np

a = np.arange(1,26).reshape(5,5)
print(a)
print(a%2==0)
print(a[a%2==0])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[False  True False  True False]
 [ True False  True False  True]
 [False  True False  True False]
 [ True False  True False  True]
 [False  True False  True False]]
[ 2  4  6  8 10 12 14 16 18 20 22 24]
